---
title: "Lab 11"
subtitle: "Advanced Computing for Policy"
format: revealjs
highlight-style: arrow
self-contained: true
---

# Lab 11

- **Objective**: Ensure our Project setup instructions, code, and analysis are clear
- **Tasks**:
    - Add setup instructions to your README
    - Usability testing of your Project with another team
    - Revise your code/documentation


---


## Document

_10 minutes_

- [Pair](../docs/pairing.md) in your Project team to add setup instructions to your README, taking someone from zero to the app running with populated data. 
- You can assume they:
    - Know Python
    - Are comfortable in the command line

[Send pull request(s) and merge.]{style="color:red;"}

---

## What is[Usability testing](https://www.nngroup.com/articles/usability-testing-101/)?

- A  [*facilitator*]{style="color:red;"} asks a [*participant*]{style="color:red;"} to perform tasks, usually using one or more specific user interfaces
- While the participant completes each task, the researcher observes the participant’s behavior and listens for feedback
- The goals of usability testing include:
    - Identifying design problems
    - Uncovering opportunities to improve
    - Learning about the target user’s behavior and preferences


---

## Today's [Usability testing](https://www.nngroup.com/articles/usability-testing-101/)

- Your Project team is going to pair up with another one
    - [Alexa-Giulio]{style="color:red;"} and [Isaura-Ibrahim]{style="color:blue;"}
    - [Angel-Fred-Arnav]{style="color:red;"} and [Sam-Charlotte-Hiro]{style="color:blue;"}
    - [Naga-Will-Krishna]{style="color:red;"} and [Arshiya-Ijaz]{style="color:blue;"}
- You'll be testing each other's Projects
    - Check/validate the usability of the code, documentation, and site.

---

## Roles: Facilitators

The Project owners will be the facilitators. Facilitators will:

- Do as little speaking/pointing/grimacing/etc. as possible
- Take notes
  - What are participants getting confused by / stuck on?
  - What steps did they need to take that aren't documented (well)?
  - What can be clearer?

---

## Roles: Participants

::: {style="font-size: 75%"}
The other team are the test participants. The task is to set up and review the Project, thinking out loud.

   1. Set up the Project.
      - Get the app running locally; you don't need to deploy it.
      - Try to follow the instructions exactly, only going back to perform missing steps when you hit a problem.
      - Everyone _should_ have read-only access to each others' BigQuery.
      - Don't worry about performing the data loading.
      - Timebox this to 20 minutes.
   1. Review the code, explaining out loud what you think it's doing.
   1. Review the site.
      - If you're unable to get it running locally, you can look at [the published site](../docs/project_teams.csv).
      - What is the site trying to convey?
      - What are your takeaways?
:::

---

### Steps

_30 minutes for each Project, with break in between_

1. Pick one Project to test first.
1. Pair up, one facilitator with one participant (roughly).
1. Participants will:
   1. Set up the Project -- Timebox this to 20 minutes.
   1. Review the code
   1. Review the site.
1. Repeat for the other Project, switching roles.

---

### Regroup

_Remaining time_

In your Project team:

1. Discuss your takeaways.
1. Revise your code/documentation.
1. [Send pull request(s) and merge.]{style="color:red;"}

[Submit links to your pull requests via CourseWorks.](https://courseworks2.columbia.edu/courses/210480/assignments)

- Make sure to include pull requests from **before and after** the usability testing.