name: Updata Microsoft Stock Price Data

on:
  schedule:
    # weekly
    - cron: "0 0 * * 0"
  # support manual trigger
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update data
        env: 
          BQ_LAB13: ${{ secrets.BQ_LAB13 }}
        run: python ${{ github.workspace }}/lab_13/update_data.py